### ISSUE TITLE
Write a Getting Started Guide

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/craftcms-boilerplate#13]
It should explain the steps required to get started with the boilerplate.

**Comment by bamccaul-dev** [comment]
Just some things to note for others that might stumble on this: 
1. Run `composer install` from root directory
1. Install Redis on server

@codewithkyle Can you perhaps put together a simple walk through of your build process for those without github actions?

**Comment by codewithkyle** [comment]
Initial readme has been written along with the addition of the `npm run setup` command.
